### PR TITLE
Adding fake for Zelda

### PR DESCRIPTION
**Pull request by snoozins**
Adding the Zelda Faker for issue #60 

used Book Faker as a template.

### CODE REVIEW

**Comment by mrstebo** [comment]
Hi @snoozins 👋 

Thanks for the PR! I'll take a look at it now. AppVeyor sometimes has a habit of failing for unknown reasons 🙈

**Comment by mrstebo** [comment]
@snoozins there was just one issue about the placement of the fields in the test. It is about keeping things standardised 😄 

I like the `=>` syntax on the methods, but I have avoided that on some of the other modules due to it code disappearing to far to the right 😅 

But in the `ZeldaFaker` it works fine 👍

**Comment by mrstebo** [comment]
I've merged a fix into master that should fix the AppVeyor issues 👍

**Comment by snoozins** [comment]
Thanks for the feedback! 

I've switched the value comparisons in the test inline 
I've merged your changes in
and switched from Expression Bodies in the ZeldaFaker class, and using Block Bodies instead

**Comment by snoozins** [comment]
I just realised you said, the Expression Bodies worked fine in the ZeldaFaker class 😅

I can switch them back :)

**Comment by mrstebo** [comment]
Nice work @snoozins :+1: 

I suppose we might as well keep the method blocks to make everything uniform.

And thanks for updating the tests too. It does mean there is duplication on the string comparisons, but I think it looks a bit cleaner :smile:

**Comment by mrstebo** [comment]
Thanks for the great work @snoozins :tada: 🙌

**Pull request merged**
